apiVersion: apps/v1
kind: Deployment

metadata:
  name: pacifista-website-deployment
  namespace: 'funixproductions'
  labels:
    app: angular
    service: pacifista-web

spec:
  replicas: 4
  selector:
    matchLabels:
      app: angular
      service: pacifista-web
  template:
    metadata:
      namespace: 'funixproductions'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: angular
        service: pacifista-web
    spec:
      containers:
        - name: angular-pacifista-web
          image: ghcr.io/pacifistamc/pacifista-website:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "300Mi"
            requests:
                cpu: "100m"
                memory: "100Mi"
          imagePullPolicy: Always

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pacifista-website-hpa
  namespace: 'funixproductions'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pacifista-website-deployment
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions'
  name: pacifista-web

spec:
  type: ClusterIP
  selector:
    app: angular
    service: pacifista-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
